//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzasIngredientes
    {
        public int PizzaID { get; set; }
        public int IngredienteID { get; set; }
        public int PizzaXIngredientes { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Ingredientes Ingredientes { get; set; }
        public virtual Pizzas Pizzas { get; set; }
    }
}
